project_name=vn-take3
servicebus_namespace=keda-virtual-node
queue_name=orders
aks_cluster_name=$project_name
AZURE_TENANT_ID="$(az account show --query tenantId -otsv)"
vnet_name=$project_name-vnet
queue_name=orders
principalId=""
user_resource_id=""
user_name="vn-take3-user"